/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MigrationsContract } from "./Migrations";
import { SampleContractContract } from "./SampleContract";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Migrations"): MigrationsContract;
      require(name: "SampleContract"): SampleContractContract;
    }
  }
}

export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  SampleContractContract,
  SampleContractInstance,
} from "./SampleContract";
