/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MigrationsContract } from "./Migrations";
import { OrderMarketplaceContract } from "./OrderMarketplace";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Migrations"): MigrationsContract;
      require(name: "OrderMarketplace"): OrderMarketplaceContract;
    }
  }
}

export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  OrderMarketplaceContract,
  OrderMarketplaceInstance,
} from "./OrderMarketplace";
